### ISSUE TITLE
Update PPA

### ISSUE THREAD

**Issue by agilgur5** [cloudtools/nymms#35]
The current PPA is over a year old, could you update it to the latest version of NYMMS?

**Comment by phobologic** [comment]
Will do!  I'll get to that today - sorry about that, I keep meaning to make that happen automatically with circle-ci, just haven't had a moment.

**Comment by phobologic** [comment]
Hey @agilgur5 - things are crazy at work still today, so I'll probably not get to this.  It's on the top of my list though as soon as things calm down - probably by Wednesday.

**Comment by phobologic** [comment]
@agilgur5 sorry for the delay - my team released https://github.com/remind101/empire this week and it's sucking up my time.  I'll get this out this weekend though.

**Comment by agilgur5** [comment]
was just about to ask again...
Cool project though!

**Comment by phobologic** [comment]
Thanks :)

**Comment by phobologic** [comment]
0.5 is published!  Let me know if it gives you any trouble.  Thanks!

**Comment by phobologic** [comment]
Hmm - it looks like there's an issue with that package, largely due to the fact that there aren't precise ubuntu packages for some of the newer packages that are required.  Not sure how to resolve that.

I'm actually thinking of moving to building docker images as well - that would make it easier to maintain dependencies.

**Comment by agilgur5** [comment]
Has nymms-common (and the other nymms-* components) not changed? It seems like only the python stuff has changed, but not sure.

I'm all for the general Docker movement, definitely easier to maintain and distribute, but I don't see how that would fix the dependency problem (since Docker is still running Linux packages after all) though

**Comment by phobologic** [comment]
nymms-common has not changed, though I should add a startup script for the API to that.  For the most part though, yeah, only the python stuff has changed.

Basically, at this point, if I want to build a 'working out of the box' precise package for NYMMS I need to build packages for at least python-schematics, python-arrow, and a few others most likely.  The # of third party dependencies went up quite a bit in this release (mostly to try and standardize on things, like schemas, times, etc - and then the API work).  Trying to figure out the best way to handle this without having to maintain like 6 non-nymms specific debian packages :)  if you have any suggestions, let me know.

**Comment by phobologic** [comment]
@agilgur5 Do you have any ideas on the best way to deal with this?  Mostly I made the packages to make it easier to deal with the startup scripts in Ubuntu.  Packaging the code as debs doesn't add a lot of value, especially on such a 'young' project.

**Comment by agilgur5** [comment]
@phobologic I'm a bit confused as I didn't write this, but you said the packages are just for startup scripts in Ubuntu and at the same time said you packaged the dependencies themselves. If they're just startup scripts, I would add those to the NYMMS package directly.

As for the dependencies, they're all Python packages, correct? There's a few ways of automating getting them then.

For people to pull the packages themselves, you can do either
1) Create a requirements.txt file
2) Create a Puppet file
3) Create a Docker image for NYMMS that installs all dependencies and allows NYMMS to run as a separate Docker container (the dependencies installed either directly by Dockerfile or by requirements.txt)

If you want to create Debian packages but not have to build/maintain them all the time, you can:
1) Use an ephemeral Docker container to automate creating the Debian packages on the user's host machine (via https://github.com/magnetikonline/dockerbuilddeb)

**Comment by agilgur5** [comment]
I feel like this should be re-opened as you said there's a problem with this package and nothing was really resolved...

**Comment by phobologic** [comment]
At this point I'm wondering if it's better to just take down the PPA and pull the example configs & init scripts into a contrib directory of the project - is this what you meant by 'add those to the NYMMS package directly'? Adding them to the github repo for others to find?

Maintaining ubuntu packages with dependencies on third party python packages (we use arrow & schematics now - both in the setup.py, and noone has made a deb of either) seems like a losing battle.  I'm actually curious how other systems handle this.

I also think it'd be really easy to create a docker image that lets you run a scheduler, probe or reactor with small changes to commands.  It makes it a lot easier to deal with dependencies without worrying about the underlying OS or package system.

**Comment by agilgur5** [comment]
Thanks for the quick response this time around @phobologic :)

Yes, that's at least part of what I meant. They certainly should be in the GitHub repo either way. I'm not totally sure on how upstart works, but wouldn't there still be a way to run them even if they were all in one package? That was the other part of what I meant. Sample configs & init scripts are certainly helpful for anyone that wants to make their own (even if they are for different distros).

I agree, that is a losing battle. http://askubuntu.com/questions/327543/how-can-a-debian-package-install-python-modules-from-pypi, specifically Solution 1.5 seems to solve this actually. Solution 2/the real solution, does run into the exact same problem you have, which is obviously tedious to do for every build.

Also agreed. The Docker build will just have to install the Python dependencies via `pip` (unless there's something I'm missing?). The only thing I was confused about here is that with one of the "more recent" commits, you moved the contents of `requirements.txt` into `setup.py` as `install_requires`. Unless I happen to be missing some recent Python/Pip changes, isn't `requirements.txt` how requirements are tracked? 

The Dockerfile should be inside this repo as well so anyone can change it if they need to (e.g. using a different base image/distro/etc), and a public Docker image can be pushed to the public Docker registry as well. The AMI might still be useful, but now it should be just as easy to get NYMMS running via Amazon Container Service as well. 

The Docker run should essentially just execute one of the services as a container (possibly as a command-line option?). Some sample scripts could potentially be added here on how to do certain things (e.g. adding suppressions), now that it's inside of Docker. Honestly, the most straightforward and modern way to do this would be to have everything go through the API which is, by default, exposed as a port on localhost, but could also be linked to other containers if a user wanted to do so (sample scripts or docs here again). The other, not-so-great option would be to run a script that calls the container directly, but, as NYMMS really is a separate service, it really should be run through the API.

1. and 2. make perfect sense, I'm not quite sure on 3. only as other users of NYMMS might prefer the PPA/Debian package route. Perhaps setting up or documenting Solution 1.5 above for whoever wants to build their own Debian package might be preferable.

If you can split this up into clear tasks, I'd very much like to help with this! :)

**Comment by phobologic** [comment]
Ok, I've finally gotten around to this.  Sorry for the delay. I've got a pull request up - #38 .  Let me know if that works for you.  Sorry for the delay - I work at an edtech company, and things have been crazy with preparing & experiencing back-to-school.  Should get more time for NYMMS here soon.

**Comment by phobologic** [comment]
The docker stuff is merged, going to go ahead and close this.  Thanks @agilgur5

**Comment by agilgur5** [comment]
Haven't used NYMMS in a long while now, but glad to see the Docker stuff working exactly as intended. Hopefully makes usage and configuration much easier for other devs!
